CREATE TABLESPACE USERZ;
CREATE TABLESPACE APPS;
CREATE TEMPORARY TABLESPACE TMP;

CREATE TABLE STUDENTS( STUDENTID INT);
CREATE TABLE EMPLOYEES (EMPLOYEEID INT);
CREATE TABLE FINANCIALS (FINANCIALID INT);
CREATE TABLE PRODUCTS (PRODUCTID INT);
CREATE TABLE SALES (SALESID INT);
CREATE TABLE PAYROLL (PAYROLLID INT);


CREATE PROFILE APPUSERS LIMIT 
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME 60
    PASSWORD_REUSE_MAX 5  
    PASSWORD_LOCK_TIME 1/24
    PASSWORD_GRACE_TIME 10;

CREATE ROLE DBAS;
CREATE ROLE FOURSEF;
CREATE ROLE TWOS;
CREATE ROLE FOURPSP;

GRANT DBA TO DBAS;

GRANT SELECT, UPDATE, INSERT, DELETE ON STUDENTS TO FOURSEF;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLOYEES TO FOURSEF;
GRANT SELECT, UPDATE, INSERT, DELETE ON FINANCIALS TO FOURSEF;

GRANT SELECT ON STUDENTS TO TWOS;
GRANT SELECT ON EMPLOYEES TO TWOS;
GRANT SELECT ON FINANCIALS TO TWOS;

GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTS TO FOURPSP;
GRANT SELECT, UPDATE, INSERT, DELETE ON SALES TO FOURPSP;
GRANT SELECT, UPDATE, INSERT, DELETE ON PAYROLL TO FOURPSP;

CREATE USER DBAONE IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ PROFILE APPUSERS;
    
GRANT DBAS TO DBAONE;
CREATE USER DBATWO IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT DBAS TO DBATWO;

CREATE USER FOURONE IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURSEF TO FOURONE;
CREATE USER FOURTWO IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURSEF TO FOURTWO;
CREATE USER FOURTHREE IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURSEF TO FOURTHREE;
CREATE USER FOURFOUR IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURSEF TO FOURFOUR;

CREATE USER SELONE IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT TWOS TO SELONE;
CREATE USER SELTWO IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT TWOS TO SELTWO;

CREATE USER ACCOUNTONE IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURPSP TO ACCOUNTONE;
CREATE USER ACCOUNTTWO IDENTIFIED BY "LONGHUGEPASSword100!!" QUOTA 500K ON USERZ TEMPORARY TABLESPACE TMP PROFILE APPUSERS;
GRANT FOURPSP TO ACCOUNTTWO;

EXECUTE AS USER = 'LAB3\FOURTHREE'
SELECT * FROM SALES
REVERT;

CONNECT FOURONE@lab3
CONNECT c##FOURONE/LONGHUGEPASSword100!!

DROP TABLESPACE USERZ;
DROP TABLESPACE APPS;
DROP TABLE STUDENTS;
DROP TABLE EMPLOYEES;
DROP TABLE FINANCIALS;
DROP TABLE PRODUCTS;
DROP TABLE SALES;
DROP TABLE PAYROLL;
DROP ROLE DBAS;
DROP ROLE FOURSEF;
DROP ROLE TWOS;
DROP ROLE FOURPSP;
DROP USER DBAONE;
DROP USER DBATWO;
DROP USER FOURONE;
DROP USER FOURTWO;
DROP USER FOURTHREE;
DROP USER FOURFOUR;
DROP USER SELONE;
DROP USER SELTWO;
DROP USER ACCOUNTONE;
DROP USER ACCOUNTTWO;
DROP TABLESPACE TMP;
DROP PROFILE APPUSERS;

